Improve customer group and channel scope empty checks
lunarphp/lunar pull request #1108
Opened 2023-06-22 08:28 UTC by alecritson

Currently the `channel` and `customerGroup` scopes only check if the passed values are not `null`, which doesn't account for whether empty arrays or collections are passed (which are accepted parameters).

The result currently would be if you passed an empty array/collection you would get nothing back.

This PR looks to add additional checks which consider those additional types.

2023-06-22 14:49 UTC, glennjacobs requested changes
Test coverage needed

2023-06-22 14:54 UTC, wychoong commented on packages/core/src/Base/Traits/HasChannels.php
> +        if (empty($channel) || (is_a($channel, Collection::class) && $channel->isEmpty())) {
i think Laravel `blank` helper function is cleaner here
https://github.com/laravel/framework/blob/b4ab62986000eaa411a22dbeb112b21c10420fdc/src/Illuminate/Support/helpers.php#L42-L62

2023-06-22 14:54 UTC, wychoong commented on packages/core/src/Base/Traits/HasCustomerGroups.php
> +        if (empty($customerGroup) || (is_a($customerGroup, Collection::class) && $customerGroup->isEmpty())) {
same

2023-06-23 07:04 UTC, alecritson commented on packages/core/src/Base/Traits/HasCustomerGroups.php
> +        if (empty($customerGroup) || (is_a($customerGroup, Collection::class) && $customerGroup->isEmpty())) {
Good shout!

2023-06-23 07:15 UTC, glennjacobs approved these changes

2023-06-23 07:53 UTC, glennjacobs approved these changes

2023-06-23 07:53 UTC, merged