Change shipping option to match the ApplyShipping functon
lunarphp/lunar pull request #1154
Opened 2023-07-25 05:28 UTC by dewebdesigns

Use the Manifest function instead of the same code that fixed the bug in #1126

2023-07-25 12:49 UTC, wychoong commented
Opps it got missed out from the previous PR. 

I think would be good to extract it into trait and update the ApplyShipping.php as well

2023-08-07 08:47 UTC, alecritson requested changes

2023-08-07 08:47 UTC, alecritson commented on packages/core/src/Pipelines/Cart/CalculateTax.php
>      private function getShippingOption(Cart $cart)
I think if we're just calling `ShippingManifest::getShippingOption($cart)` in this method then we can just do away with this private method altogether and just call it on line 62

2023-08-07 08:55 UTC, wychoong commented on packages/core/src/Pipelines/Cart/CalculateTax.php
>      private function getShippingOption(Cart $cart)
that's a good one

2023-08-17 03:52 UTC, closed without merging