Italian translation of the hub
lunarphp/lunar pull request #1290
Opened 2023-10-06 07:32 UTC by rinodrummer

To improve the usability, me and @sebhd1 decided to dive in the Italian translation of the hub.

We translated all the entries in the localization files, but noticed that most of the UI components have un-wrapped texts that make them hard to translate.

I think that a guide line must be discussed to define which namespaces must be attributed to some components and must enforce to use `__()` whenever possible, even in component labels, placeholders and so on when new hub section are introduced.

We are willing to help and always open to discussions!

2024-05-06 19:57 UTC, glennjacobs commented
@rinodrummer Apologies for the late review. This looks good, but I can see 6 TODOs outstanding in the code that will need addressing before this can be merged. Thanks.

2024-05-06 20:18 UTC, glennjacobs requested changes
Resolve TODOs

2024-05-07 06:46 UTC, rinodrummer commented
Hi @glennjacobs I'll give a look at them in the weekend!

2024-05-22 07:46 UTC, glennjacobs commented
> Hi @glennjacobs, I'll give a look at them in the weekend!

Hi @rinodrummer, I'm going to change this PR to draft until we have it ready for review again.

2024-07-05 10:23 UTC, glennjacobs commented
I will look to merge translations once we've hit a beta release, as there may be some changes required.

2024-11-19 22:57 UTC, glennjacobs commented
I've just realised I assumed this was for v1.0, but it's actually targeting 0.8.

Would you have any interest in doing v1.0?

2025-02-14 18:18 UTC, glennjacobs commented
As we're not looking to add to 0.8 now, I am going to close this PR.

2025-02-14 18:18 UTC, closed without merging

2025-06-07 13:33 UTC, vitalijalbu commented
any updates guys on italian translations?

2025-06-12 08:58 UTC, rinodrummer commented
Sorry guys, me and Seb (the other contributor) have been involved in some career issues.

We will do our best to complete this PR as soon as possible, but right now we cannot work on it.