Feature - New config on StandardMediaConversions
lunarphp/lunar pull request #1565
Opened 2024-02-16 09:59 UTC by lguichard

This PR remove hard coded value and create a new config

2024-02-16 10:05 UTC, lguichard commented
```sh
Run shivammathur/setup-php@v2
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✗ PHP Could not setup PHP [8](https://github.com/lunarphp/lunar/actions/runs/7928914847/job/21648120617?pr=1565#step:3:9).2
Error: The process '/usr/bin/bash' failed with exit code 1`
```
@glennjacobs 
The CI don't like me xD

2024-02-16 10:06 UTC, glennjacobs commented
Why do we need this? Lunar uses it for images, hence the collection name is called `images`.

2024-02-16 10:24 UTC, lguichard commented
I discover this hard coded value during the demostore conversion. The products seeder used media collection name "products". 

If they devs add Lunar package on existing project and that already use 'images' name, they need to change the default value. In big e-commerce website, we need to dispatch medias on multi storage buckets to optimize CDN etc... I think it might be necessary to split collection name to organize assets by Model.

2024-02-16 10:30 UTC, glennjacobs commented
@alecritson can I have your opinion, please?

Things to consider...

- Will this not break the admin panel, unless we introduce the config there also?
- I don't think we want to change the default 'images' collection name on other models. Sure, allow a dev to change it, but I don't believe we need to change them in our config.

2024-02-16 10:47 UTC, lguichard commented
@glennjacobs, to ensure backward compatibility probably better if we keep only media_collection => 'images' allow a dev change it.

2024-03-11 22:15 UTC, glennjacobs requested changes

2024-03-11 22:15 UTC, glennjacobs commented on packages/core/config/media.php
> +        'videos' => 'videos',
I don't think we need `videos` in the config, considering the system doesn't actually use it. It's only used in tests, so I think it would be misleading to include it here.

2024-05-22 08:38 UTC, alecritson commented
@glennjacobs Doesn't look like we've hit every instance of `SpatieMediaLibraryImageColumn` when updating the `collection` method to config.

2024-05-22 08:50 UTC, glennjacobs commented
> @glennjacobs Doesn't look like we've hit every instance of `SpatieMediaLibraryImageColumn` when updating the `collection` method to config.

Should be sorted.

2024-05-22 08:53 UTC, alecritson approved these changes

2024-05-22 08:56 UTC, glennjacobs approved these changes

2024-05-22 09:19 UTC, merged