Consider authenticated user when fetching cart from session
lunarphp/lunar pull request #1742
Opened 2024-05-13 08:22 UTC by alecritson

Currently the cart session manager doesn't try to fetch a users most recent and active cart if they don't already have a cart id in the session.

This PR adds a check to fallback on a users active cart before trying to create anything new.

2024-05-16 10:34 UTC, glennjacobs requested changes
This should have a test.

2024-05-16 11:11 UTC, glennjacobs approved these changes

2024-05-16 12:29 UTC, merged

2024-05-23 11:35 UTC, wychoong commented
this breaks the `CartSession::forget()` functionality where after forgetting the cart, it fetches by user

my testing
![image](https://github.com/lunarphp/lunar/assets/67364036/5a9734c1-3c58-4582-83a7-bf793ba53f9b)

my logs
```
[2024-05-23 11:34:35] local.INFO: delete  << calling CartSession::forget()
[2024-05-23 11:34:35] local.INFO: fetch from session  
[2024-05-23 11:34:35] local.INFO: fetch from user  
```

2024-05-23 12:50 UTC, glennjacobs commented
> this breaks the `CartSession::forget()` functionality where after forgetting the cart, it fetches by user
> 
> my testing ![image](https://private-user-images.githubusercontent.com/67364036/333165711-5a9734c1-3c58-4582-83a7-bf793ba53f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Njg4OTEsIm5iZiI6MTcxNjQ2ODU5MSwicGF0aCI6Ii82NzM2NDAzNi8zMzMxNjU3MTEtNWE5NzM0YzEtM2M1OC00NTgyLTgzYTctYmY3OTNiYTUzZjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEyNDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0YmJlY2U0ZjcxYmMwOWJjNzAyZDY0ZTg2MmVmOWMyZDg4Mjg5Yzk4MDliMjRlNjgyZWIyMjM2MjIzYTVhNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LjJoE4b1NvMv323E22kX5yV0OoNlXtJ6mZcp6yFy3_c)
> 
> my logs
> 
> ```
> [2024-05-23 11:34:35] local.INFO: delete  << calling CartSession::forget()
> [2024-05-23 11:34:35] local.INFO: fetch from session  
> [2024-05-23 11:34:35] local.INFO: fetch from user  
> ```

I get the problem. But could you explain your use case for `CartSession::forget()`?

2024-05-23 13:07 UTC, wychoong commented
My use case is to delete a cart belongs to the user. 
And also sort of one click to empty the cart. 

Although as workaround we can loop to remove the cart lines, there are more things to clear, eg: addresses, shipping option, coupon, meta, cache?, etc. 

A simple forget and delete will be more performant

2024-05-23 13:30 UTC, alecritson commented
@wychoong Myself and Glenn discussed this and propose the following solution: https://github.com/lunarphp/lunar/pull/1775