Merge 0.8
lunarphp/lunar pull request #1743
Opened 2024-05-13 08:25 UTC by glennjacobs

Please describe your Pull Request as best as possible, explaining what it provides and why it is of value, referencing any related Issues.

Try to include the following in your Pull Request, where applicable...

- Documentation updates
- Automated tests

2024-05-13 10:21 UTC, glennjacobs commented
@alecritson do you think we should have the `.github` folders on each package?

2024-05-20 07:06 UTC, alecritson requested changes

2024-05-20 07:06 UTC, alecritson commented on packages/admin/src/Models/Staff.php
> +        return "https://www.gravatar.com/avatar/$hash?d=mp";
Through Lunar we usually do `"{$hash}"` when using string interpolation

2024-05-20 07:31 UTC, glennjacobs commented on packages/admin/src/Models/Staff.php
> +        return "https://www.gravatar.com/avatar/$hash?d=mp";
This was just a merge, but i can update it.

2024-05-20 07:45 UTC, alecritson commented
> @alecritson do you think we should have the `.github` folders on each package?

I assume we need them because they have specific workflows which auto close PRs?

2024-05-20 07:52 UTC, glennjacobs commented
> > @alecritson do you think we should have the `.github` folders on each package?
> 
> I assume we need them because they have specific workflows which auto close PRs?

Yeah, they're to auto-close PRs on the read-only repos. It could be argued that all the packages should have them.

2024-05-22 07:10 UTC, alecritson submitted a review, later dismissed

2024-05-22 07:11 UTC, alecritson commented on tests/core/Unit/Search/ProductOptionIndexerTest.php
> +    $this->assertEquals($productOption->name->en, $data['name_en']);
Just realised after I approved that this has been reverted to PHPUnit syntax.

2024-05-22 16:16 UTC, alecritson approved these changes

2024-05-22 20:08 UTC, merged