Settings - Manage Product Options
lunarphp/lunar pull request #419
Opened 2022-07-25 23:37 UTC by adam-code-labx

See #406 
Duplicated Product Feature section to manage product options.

<img width="2205" alt="Screenshot 2022-07-26 at 00 32 54" src="https://user-images.githubusercontent.com/53559175/180892102-4aa25f31-cf50-4201-a97b-12906c1ba820.png">

Validation and tests + refactor still to do so opening up this PR in draft.

2022-07-26 10:24 UTC, glennjacobs commented
We'll have to manually test this to ensure it's all good, but I do welcome the idea of editing product options globally in the settings area.

2022-07-26 11:15 UTC, adam-code-labx commented
Sure there is a still a little more work on this one as currently copied over from manage features should be completed by tomorrow. Would be nice to see both the product options and features at least get merged to the new develop branch.

2022-07-26 22:40 UTC, adam-code-labx commented
@glennjacobs Ok this one is ready for review.
I removed the manage features and created a few tests so should be good for the next beta.
Unless there is anything else you need me to add for this one?

2022-09-02 09:12 UTC, markmead requested changes
Hey, @adam-code-labx I'm not too clued up on this PR so my testing comes from being an actual user, here are a few things I spotted.

- How do you know what options have been added to a variant? 
There doesn't seem to be anything in the UI to tell me.
- How do I add options to a variant that already exists?
- When creating a new option value, I am shown this error.
`Call to undefined method GetCandy\Models\ProductOptionValue::productOption()`

Some of the UI looked off as well.

Extra border under the "Delete option" button.

<img width="276" alt="Screenshot 2022-09-02 at 09 48 43" src="https://user-images.githubusercontent.com/50486078/188105860-411322bf-ce36-4259-8ec2-97ff7c55486d.png">

Extra border under the "Delete option value" button.

<img width="247" alt="Screenshot 2022-09-02 at 09 48 49" src="https://user-images.githubusercontent.com/50486078/188106003-992919e7-8f9d-461c-98e1-0a157c903fba.png">

When pressing "Enter" after filling out the first input it should submit the form, currently, it shows the next translation.

<img width="709" alt="Screenshot 2022-09-02 at 09 49 59" src="https://user-images.githubusercontent.com/50486078/188106054-7bf0b184-d232-429d-8536-6cc63cb9dc7a.png">

Should this be empty? And there seems to be a missing translation.

<img width="974" alt="Screenshot 2022-09-02 at 09 50 17" src="https://user-images.githubusercontent.com/50486078/188106154-7c67bd5e-9a79-4b22-b6ae-ef9e120284a7.png">

---

I seem to remember seeing a way to associate options with different models, has that been removed?

2022-09-02 10:17 UTC, adam-code-labx commented
Thanks @markmead I will pull this branch down over the weekend and update those issues you mentioned.

Was thinking about perhaps extracting this to an abstract ListBuilder similar to #481 then setup each list as a component where ever we need it, for example Product features / Product options / Collections as there is currently far too much responsibility handled directly in the blade templates. Would be good to extract the actions as well.

Regarding this question
"How do I add options to a variant that already exists?"

Not quite sure what you mean on this one, as this is a global way to manage product options, at this level I don't think we need to be concerned about the variants.

2022-09-02 13:05 UTC, markmead commented
Sorry @adam-code-labx, that question is irrelevant. I was getting confused between options and attributes, my bad!

2022-09-05 09:08 UTC, glennjacobs commented
Hi @adam-code-labx any update on this from @markmead 's review above?

2022-10-07 08:06 UTC, alecritson commented
@markmead @adam-code-labx 

I've done some tweaks to this this morning to try push it over the line as I think it's good enough to get in and be a useful addition to the hub, we can always improve on it down the line.

Changes:

- Add `handle` input to allow users to specify this manually, rather than auto-generating it.
- Addressed style updates as Mark mentioned
- Fixed some translations and the incorrect relationship reference.

2022-12-15 09:30 UTC, glennjacobs commented
Tried to add two options both with the same name

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/647407/207823536-00507cfd-0a5a-49d2-b9b7-6068d658d3e1.png">

2022-12-15 09:31 UTC, glennjacobs commented
Clicking "Add option value" does nothing

<img width="275" alt="image" src="https://user-images.githubusercontent.com/647407/207823848-f7cad56c-517b-4bad-acfd-336d46ac8c68.png">

2022-12-15 10:21 UTC, glennjacobs commented
Capitalisation isn't consistent

<img width="330" alt="image" src="https://user-images.githubusercontent.com/647407/207834343-1ed56c92-658a-4bde-9002-557d83dc8674.png">

2022-12-15 10:21 UTC, glennjacobs commented
Can we show a count of the values for each option?

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/647407/207834435-24a41d79-6320-4a1e-a595-7393d7bf696c.png">

2022-12-15 11:29 UTC, glennjacobs commented on packages/admin/resources/views/livewire/components/settings/product/options/index.blade.php
> +            <x-hub::input.group label="Name" for="optionName" :error="$errors->first('newProductOption.name.'.$this->defaultLanguage->code)">
Should "Name" be translated?

2022-12-15 11:29 UTC, glennjacobs commented on packages/admin/resources/views/livewire/components/settings/product/options/index.blade.php
> +                        placeholder="Size"
Placeholder not translated

2022-12-15 11:29 UTC, glennjacobs commented on packages/admin/resources/views/livewire/components/settings/product/options/index.blade.php
> +            <x-hub::button>Create option</x-hub::button>
Translation required

2022-12-15 12:08 UTC, glennjacobs approved these changes

2022-12-15 12:11 UTC, merged