Continue sidebar menu grouping feature
lunarphp/lunar pull request #421
Opened 2022-07-27 01:05 UTC by adam-code-labx

@glennjacobs I can see this one was started so I have continued this grouping feature.
If we can't make the next beta release then please include in the new develop branch to avoid switching branches 😂

2022-07-27 09:29 UTC, markmead commented on packages/admin/resources/views/components/menu-list.blade.php
> -                <ul class="mt-2 space-y-2">
Removing `mt-2` has caused the menu to be squashed with the menu title.

2022-07-27 09:32 UTC, markmead commented on packages/admin/resources/views/components/menu-list.blade.php
> +<div class="space-y-4" x-data="{ type: '{{ $type }}' }">
I think we should be more declarative here, `type` doesn't mean much. Switching to `menuType` would help.

2022-07-27 09:36 UTC, markmead commented on packages/admin/resources/views/components/menu-list.blade.php
> +                        <li :class="{ 'items-center': !showExpandedMenu }">
Do you have a screenshot of how this looks? 📸

2022-07-27 09:39 UTC, adam-code-labx commented on packages/admin/resources/views/components/menu-list.blade.php
> +                        <li :class="{ 'items-center': !showExpandedMenu }">
sure 👍 
<img width="332" alt="Screenshot 2022-07-27 at 10 37 58" src="https://user-images.githubusercontent.com/53559175/181215608-a6c17c47-17eb-4904-ab6e-918d7b6335be.png">

2022-07-27 10:02 UTC, markmead commented on packages/admin/resources/views/components/menu-list.blade.php
> +                        <li :class="{ 'items-center': !showExpandedMenu }">
I could be dumb here but that doesn't look much different from the current implementation without `:class="{ 'items-center': !showExpandedMenu }"`

2022-07-27 10:03 UTC, markmead commented on packages/admin/resources/views/livewire/sidebar.blade.php
> +                menuType="main_menu"
I'm being picky here (sorry) but could this be passed through as `menu-type`, I believe you won't need to change the `$menuType` used elsewhere.

2022-07-27 10:17 UTC, adam-code-labx commented on packages/admin/resources/views/components/menu-list.blade.php
> +                        <li :class="{ 'items-center': !showExpandedMenu }">
Your right no difference at all will remove it, in my defence I copied this over from `sidebar.blade.php` 😬

2022-08-26 08:16 UTC, markmead requested changes
LGTM! Just a few small tweaks where the branch has got outdated.

2022-08-26 08:16 UTC, markmead commented on packages/admin/resources/views/components/menu-list.blade.php
> +                           x-on:mouseleave="showTooltip = false"
This approach was switched out to use the `group` class in Tailwind CSS -https://github.com/getcandy/getcandy/blob/develop/packages/admin/resources/views/livewire/sidebar.blade.php

2022-08-26 08:16 UTC, markmead commented on packages/admin/resources/views/components/menu-list.blade.php
> +            <ul class="ml-1 space-y-2">
Why the addition of `ml-1`?

2022-08-26 08:43 UTC, adam-code-labx commented on packages/admin/resources/views/components/menu-list.blade.php
> +                           x-on:mouseleave="showTooltip = false"
No problem will check this one over the weekend and update.

2022-08-26 08:45 UTC, adam-code-labx commented on packages/admin/resources/views/components/menu-list.blade.php
> +            <ul class="ml-1 space-y-2">
Good question it was almost a month ago so will check once I have merged  the latest changes 😆

2022-08-27 09:57 UTC, adam-code-labx commented on packages/admin/resources/views/components/menu-list.blade.php
> +            <ul class="ml-1 space-y-2">
The reason. ml-1 was added was to make sure the menu items line up with the dashboard.

<img width="608" alt="Screenshot 2022-08-27 at 10 54 39" src="https://user-images.githubusercontent.com/53559175/187025171-9cfe3e2f-ede4-49c3-b0a2-9fbf8e290024.png">

2022-08-27 10:16 UTC, adam-code-labx commented
@markmead Tooltip updated to group hover.

I have quite a few ideas on improving this menu grouping feature.
Already implemented part of this for my client customisations the ability to dynamically populate the menu from the page components.

With this I am introducing a new Resource class to handle the menu and PageComponent to handle the view.
The page CRUD components extend the resource so only need to define the navigation once.

```php
<?php

namespace GetCandy\Hub\Http\Livewire\Pages\Products;

use GetCandy\Hub\Http\Livewire\PageComponent;

abstract class ProductsResource extends PageComponent
{
    protected static string $navigationLabel = 'Products';

    protected static string $navigationIcon = 'shopping-cart';

    protected static string $navigationGroup = 'catalogue';
    
    protected static int $navigationPosition = 3;

    public function mount()
    {
        static::setTitle('Products');
    }
}
```

```php
<?php

namespace GetCandy\Hub\Http\Livewire;

use Livewire\Component;

class PageComponent extends Component
{
    protected static string $view;

    protected static string $navigationLabel;

    protected static string $navigationIcon;

    protected static string $navigationGroup;
    
    protected static int $navigationPosition;

    protected static array $params = [];

    public static function setTitle(string $title)
    {
        self::$params['title'] = $title ?? 'Page';
    }

    /**
     * @param  array  $params
     */
    public static function setParams(array $params): void
    {
        self::$params = array_merge(self::$params, $params);
    }

    /**
     * Render the livewire component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('adminhub::livewire.pages.'.static::$view)
            ->layout('adminhub::layouts.app', static::$params);
    }
}
```

This is how it looks currently on my side.
<img width="278" alt="Screenshot 2022-08-27 at 11 04 03" src="https://user-images.githubusercontent.com/53559175/187025558-b4f7cd43-8b6e-46f5-a83f-2a4ed646c975.png">

If your interested in including this let me know, I can either refactor the existing page components or create another PR for this one 😜

2022-09-05 09:00 UTC, glennjacobs commented
@adam-code-labx got a few bugs to sort on this one.

Firstly, the styling seems to have gone a bit wrong in places.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/647407/188410375-4174bd2e-6589-42c1-9662-bfbb18211384.png">

The tooltips do not align correctly and are inconsistent. And the icon placement is not centered in the light blue boxes.

Also, it no longer remembers your preference when contracting the menu. If you refresh it will forget and go back to default (expanded).

2022-09-05 11:28 UTC, adam-code-labx commented
@markmead I was about to push a fix but now lots of merge conflicts 😂

2022-09-05 11:34 UTC, adam-code-labx commented
@markmead you can review here then apply the changes just put up temp branch, this is the only commit for the changes.
https://github.com/adam-code-labx/getcandy/commit/63901694cc392cd53793cbc293c1d13a30701763

Currently you do have an issue with the setting alignment should only be applied to the main menu items
<img width="332" alt="Screenshot 2022-09-05 at 12 31 50" src="https://user-images.githubusercontent.com/53559175/188439315-100957eb-5964-46b9-b5ce-a5e28bfc2c05.png">

Also the focus when in the settings menu should be only the settings menu see my collapsedMainMenu override, which will ignore persist if you are in a settings section.

2022-09-05 12:10 UTC, markmead commented
Sorry, @adam-code-labx I was asked to take a quick look as we're getting PRs merged in today!

Welcome to make those changes/fixes, but we want a working persist more than we want the settings menu being displayed by default when on `/settings`.

2022-09-06 06:49 UTC, markmead commented
Looks good! @adam-code-labx

Do need to run `yarn production` as the JS is now 37k lines long 😅 

Question for @glennjacobs do we want the side menu auto collapsing when a user is on `/hub/settings/*`?
<img width="1473" alt="Screenshot 2022-09-06 at 07 42 55" src="https://user-images.githubusercontent.com/50486078/188564832-952e911f-1004-4833-8cdd-e1e8dc5adc6e.png">

If we do take that approach, should the same happen for collections and variants?
<img width="1473" alt="Screenshot 2022-09-06 at 07 44 46" src="https://user-images.githubusercontent.com/50486078/188565238-6744833b-961a-4fa4-8076-b2ed0faf1b22.png">
<img width="1473" alt="Screenshot 2022-09-06 at 07 43 49" src="https://user-images.githubusercontent.com/50486078/188565245-c2895759-8e04-434f-ad4b-5372c157788a.png">

Additionally, "Orders List" does that sound right? I feel like it should be "Orders" but then you have the issue of the sub-menu header being the same. Looking at what Shopify does, "Orders" is a link and the sub-menu header.
<img width="1473" alt="Screenshot 2022-09-06 at 07 47 59" src="https://user-images.githubusercontent.com/50486078/188565693-5c9bae03-4832-4be5-8867-4b43568af778.png">

2022-09-06 07:57 UTC, adam-code-labx commented
Ooops that’s what happens with `npm run watch` 😆

2022-09-06 08:03 UTC, adam-code-labx commented
@markmead @glennjacobs collapsing the main menu if there is a sub menu open is a great idea to focus on the section you are on.

For orders I would change the group name to be something like Sales which would eventually have the following:

Sales
  - Customers
  - Discounts
  - Orders 
  - Carts

2022-09-06 08:10 UTC, adam-code-labx commented
I feel like soon we will need to consider accordion style collapsible especially once we have some addons in place.

2022-09-06 08:13 UTC, glennjacobs commented
> Question for @glennjacobs do we want the side menu auto collapsing when a user is on /hub/settings/*?

I think we can, but only for smaller screen sizes. If there is enough room, it should remain expanded (if that was their preference).

2022-09-06 09:14 UTC, adam-code-labx commented
Ok so I should revert the settings commit?
Then just let the user decide? 

Let me know if you would like any further changes or @markmead you plan to finish this one?

2022-09-06 10:03 UTC, glennjacobs commented
> For orders I would change the group name to be something like Sales which would eventually have the following:
> 
> Sales
> 
> * Customers
> * Discounts
> * Orders
> * Carts

I think "Sales" works, go with that.

2022-09-06 11:02 UTC, markmead commented
All good for you to finish this one up 🏁 @adam-code-labx

2022-09-06 16:33 UTC, adam-code-labx commented
@markmead @glennjacobs 
Ok should be good to merge now.

2022-10-04 09:02 UTC, jonathangustafssonax commented
@markmead is there any blocker to merge this in to main?

2022-10-04 09:06 UTC, glennjacobs commented
> @markmead is there any blocker to merge this in to main?

We have been testing different menu layouts internally. This is our preference currently. 

https://ui-menu.vercel.app/

Ignore the style, it's more about how the menu works. So you'll see the sections are actually replaced with top-level menu items. We are likely to take this route, but was keeping this PR open until we made a firm decision.

2022-11-11 10:54 UTC, glennjacobs commented
Closing in favour of #680

2022-11-11 10:54 UTC, closed without merging