Improve UX for image manager
lunarphp/lunar pull request #806
Opened 2023-01-12 14:11 UTC by rubenvanerk

#787 but targeting main

2023-01-16 07:51 UTC, alecritson requested changes

2023-01-16 07:51 UTC, alecritson commented on packages/admin/resources/views/components/input/toggle.blade.php
> +    @disabled($disabled ?? true)
Looks like this directive was added in Laravel 9, we're still trying to support L8 so features need to be backwards compatible.

2023-01-17 19:28 UTC, rubenvanerk commented on packages/admin/resources/views/components/input/toggle.blade.php
> +    @disabled($disabled ?? true)
Sorry about that, reverted it!

2023-01-18 07:38 UTC, alecritson approved these changes
Thanks for this @rubenvanerk I spotted another instance of `@disabled` but correct it, looks good will get it in :)

2023-01-18 07:38 UTC, merged