Discount - fixed `AmountOff` to share by percentage
lunarphp/lunar pull request #949
Opened 2023-04-17 19:54 UTC by ryanmitchell

We're running into issues where the items in certain carts combined with discounts were giving negative subtotals due to how the amount off (fixed value) discount was being calculated.

I've re-worked the discount to take a different approach. I've also added test coverage for one of the basket combinations that caused us issues.

2023-04-18 06:43 UTC, alecritson commented on packages/core/src/DiscountTypes/AmountOff.php
> +                $line = $cart->lines->first(function ($line) use ($remaining) {
Should we be checking over all lines here? Shouldn't this just be eligible lines?

2023-04-18 06:44 UTC, ryanmitchell commented on packages/core/src/DiscountTypes/AmountOff.php
> +                $line = $cart->lines->first(function ($line) use ($remaining) {
I think it should just be eligible but it was originally all lines so I didnt want to change it!

2023-04-18 06:47 UTC, alecritson commented on packages/core/src/DiscountTypes/AmountOff.php
> +                $line = $cart->lines->first(function ($line) use ($remaining) {
Yeah looks like a mistake there 😅 Happy for it to be just eligible lines and then maybe it can be added to the logic above it to keep it concise

2023-04-18 07:04 UTC, ryanmitchell commented on packages/core/src/DiscountTypes/AmountOff.php
> +                $line = $cart->lines->first(function ($line) use ($remaining) {
No problem - thats updated

2023-04-21 10:34 UTC, alecritson commented on packages/core/src/DiscountTypes/AmountOff.php
> -            if ($line->discountTotal->value > $amount) {
I can see this was removed, was there a reason behind this? If there is a previous discount which is better than this one, we don't want this one to apply I don't think.

2023-04-21 10:40 UTC, ryanmitchell commented on packages/core/src/DiscountTypes/AmountOff.php
> -            if ($line->discountTotal->value > $amount) {
The way it's working now is to compound the discount... so if you already have a discounted price then it uses that to work out what share of the discount you take. 

Ultimately you are still getting the same 'value' out of the discount as its shared across all the lines.

2023-04-21 11:01 UTC, alecritson commented on packages/core/src/DiscountTypes/AmountOff.php
> -            if ($line->discountTotal->value > $amount) {
I think myself and glenn spoke about this and not having discounts stack as it adds complexity, what do you think @glennjacobs ?

2023-04-21 15:43 UTC, ryanmitchell commented on packages/core/src/DiscountTypes/AmountOff.php
> -            if ($line->discountTotal->value > $amount) {
Just a heads up that if that’s the intention it’s not in place on the percentage discount - they compound.

2023-04-25 09:58 UTC, glennjacobs commented on packages/core/src/DiscountTypes/AmountOff.php
> -            if ($line->discountTotal->value > $amount) {
@alecritson Compounding discounts do indeed add a lot of complexity. It would be easier to avoid it.

@ryanmitchell is this something you need for your project? Trying to understand what impact it might have if we didn't support compounding discounts.

2023-04-25 10:26 UTC, ryanmitchell commented
I don’t need it.On 25 Apr 2023, at 10:58, Glenn Jacobs ***@***.***> wrote:﻿
@glennjacobs commented on this pull request.



In packages/core/src/DiscountTypes/AmountOff.php:
>          $remaining = $value;
 
         $affectedLines = collect();
 
         foreach ($lines as $line) {
-            if ($line->subTotal->value < $roundedChunk) {
-                $amount = $roundedChunk - ($roundedChunk % $line->subTotal->value);
-            } else {
-                $amount = $roundedChunk;
-            }
-
-            // If this discount already has a greater discount value
-            // don't add this one as they already have a better deal.
-            if ($line->discountTotal->value > $amount) {

@alecritson Compounding discounts do indeed add a lot of complexity. It would be easier to avoid it.
@ryanmitchell is this something you need for your project? Trying to understand what impact it might have if we didn't support compounding discounts.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-02 08:59 UTC, ryanmitchell commented
Do you guys plan to work on this or do you need me to update the code here to avoid compounding?

2023-05-03 07:13 UTC, alecritson commented
@ryanmitchell I think if you update what you changed and then we can take a look and see if anything needs changing on a new PR or something.

2023-05-03 07:15 UTC, ryanmitchell commented
No problem - thats done - https://github.com/lunarphp/lunar/pull/949/commits/f4d2fd94d03f91f0165f0a282e0e62d616f9ea9e

2023-05-03 07:21 UTC, ryanmitchell commented
Seems like can_apply_multiple_different_discounts needs to be updated (or removed) as it is a test that assumes compounding?

2023-05-10 15:47 UTC, glennjacobs commented
> Seems like can_apply_multiple_different_discounts needs to be updated (or removed) as it is a test that assumes compounding?

@alecritson could you take a look at this?

2023-05-11 09:55 UTC, alecritson commented
> > Seems like can_apply_multiple_different_discounts needs to be updated (or removed) as it is a test that assumes compounding?
> 
> @alecritson could you take a look at this?

From what I can see the compounding is due to it being a percentage, not fixed price, which from what I remember you greenlit? If you could cast your eyes on it too that would be great.

2023-06-26 18:08 UTC, ryanmitchell commented
Any thoughts on this? Its still causing issues for us on our live sites.

2023-08-18 11:38 UTC, glennjacobs commented
@ryanmitchell Alec and I have discussed this one and we're going to run with your suggestion. Could you re-target this PR to `main` and we'll look to get it in, thanks.

2023-08-18 11:45 UTC, glennjacobs requested changes
Retarget to `main`

2023-08-18 12:24 UTC, ryanmitchell commented
Closing for #1207

2023-08-18 12:24 UTC, closed without merging